
# ignore all warnings from all pods
inhibit_all_warnings!


target 'WeeklyiPad' do
    
    pod 'AFNetworking', '~> 3.0'
    pod 'YTKNetwork'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'MagicalRecord'
    pod 'SSZipArchive'
    pod 'MJExtension'
    
    
end
